### ISSUE TITLE
Searching large ontologies

### ISSUE THREAD

**Issue by danielapoliveira** [UAMS-DBMI/MIREOT-plugin#1]
Hi,
I'm trying to add classes from the NCI Thesaurus OBO Edition ontology. The ontology loads and the search returns the desired results. However, when I try to drag and drop the class into my ontology, I get NullPointerException. Here is the [protege.log](https://github.com/UAMS-DBMI/MIREOT-plugin/files/1703854/protege.log) with the error.

Is there any fix for this issue?

**Comment by utecht** [comment]
Which version of the plugin are you using?

I ask because I fixed a null pointer related to missing version IRIs a few weeks ago in version 2.1.4.

**Comment by danielapoliveira** [comment]
I'm using 2.1.4. I cloned the repository today so I believe it's the latest.

**Comment by utecht** [comment]
What is the URI for the ontology you are copying classes from.

**Comment by danielapoliveira** [comment]
http://purl.obolibrary.org/obo/ncit.owl

**Comment by utecht** [comment]
![image](https://user-images.githubusercontent.com/1213539/35935390-f1487406-0c05-11e8-9688-4cca26d23ae8.png)

I'm able to drag and drop a few arbitrary classes over, which specific classes are giving you the error?

**Comment by danielapoliveira** [comment]
I have been trying searching for "gene symbol" and dragging the only result. But now I tried you the one you have there and I get the same error. 

By the way, I'm using the Linux version of Protégé (5.1.0).

**Comment by utecht** [comment]
I just downloaded Protege 5.1.0 instead of 5.2.0 which I had been using earlier, and while I'm not getting a null pointer exception it isn't working anymore.

Can you update to version 5.2.0 of protege and see if that fixes the issue?

**Comment by danielapoliveira** [comment]
I updated and now it's working. I didn't realise that I didn't have the latest version. Thanks for your help!
